version: '3.7'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "DESCRIBE KEYSPACES"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - scylla_data:/var/lib/scylla
  
  kt:
    image: evilgenius13/kt:prod
    depends_on:
      - scylla
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - AXIOM_KEY=${AXIOM_KEY}
      - AXIOM_TRACE_KEY=${AXIOM_TRACING_KEY}
      - AXIOM_DATASET=${AXIOM_DATASET}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_tts
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    secrets:
      - google_tts

secrets:
  google_tts:
    external: true

volumes:
  scylla_data:
