version: '3.1'

services:
  kt:
    image: evilgenius13/kt:extralife
    container_name: kt
    environment:
      - DISCORD_TOKEN=your_discord_token_here

  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"