version: '3.1'

services:
  kt:
    image: evilgenius13/kt:dev
    container_name: kt
    environment:
      - DISCORD_TOKEN=yourtokenhere

  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"