version: '3.7'
# Development environment for ScyllaDB and Redis
services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
          
  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  scylla_data:
  redis_data:
