version: '3.7'
# Development environment for ScyllaDB, Redis, and Axiom Starfire
services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
          
  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD= ${REDIS_PASSWORD}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
  
  starfire:
    image: evilgenius13/axiomstarfire:latest
    container_name: starfire
    ports:
      - "8010:8000"
    environment:
      - AXIOM_KEY=${AXIOM_KEY}
      - AXIOM_DATASET=${AXIOM_DATASET}

volumes:
  scylla_data:
  redis_data:
