version: '3.1'

services:
  kt:
    image: evilgenius13/kt:extralife
    container_name: kt
    environment:
      - DISCORD_TOKEN=your_discord_token_here
    # Optional
    # cpus: '1'
    # mem_limit: 512m
