version: '3.7'

services:
  kt:
    image: evilgenius13/kt:dev
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure

  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    ports:
      - "9042:9042""