version: '3.7'

services:
  scylla:
    image: scylladb/scylla:5.2
    container_name: scylla
    command: --developer-mode=1 --smp 1
    ports:
      - "9042:9042"
    volumes:
      - scylla_data:/var/lib/scylla
    healthcheck:
      test: ["CMD-SHELL", "cqlsh -e 'DESCRIBE KEYSPACES' || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 180s # wait for scylla to start
    deploy:
      placement:
        constraints:
          - node.hostname == eg-1 # need to change this to the name of your node
  
  kt:
    image: evilgenius13/kt:prod
    container_name: kt
    depends_on:
      - scylla
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - AXIOM_KEY=${AXIOM_KEY}
      - AXIOM_TRACE_KEY=${AXIOM_TRACING_KEY}
      - AXIOM_DATASET=${AXIOM_DATASET}
      - OPENAI_KEY=${OPENAI_KEY}
      - OPENAI_ASSISTANT=${OPENAI_ASSISTANT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_tts
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
      restart_policy:
        condition: on-failure
    secrets:
      - google_tts
    
  redis:
    image: redis:7.2.4
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
      restart_policy:
        condition: on-failure

secrets:
  google_tts:
    external: true

volumes:
  scylla_data:
  redis_data:
